name: Daily Stock Data Update

on:
  schedule:
    - cron: '0 16 * * *'  # Runs at 16:00 UTC (1:00 AM JST) every day

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run fetch and chart
      run: |
        go run cmd/fetch/main.go 9064.T,7203.T,6752.T,9501.T,8136.T,9064.T,2220.T,5253.T,5032.T,4661.T,9432.T,3778.T,3382.T | go run cmd/chart/main.go > index.html

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update stock data [skip ci]" && git push) 